#!/bin/bash

clear

base64 -d <<<"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCkBAQCAgQEBAICBAQEBAQEBAICAgIEBAQEBAQCAgICBAQEBAQEBAICBAQEAgIEBAQCAgICAgICAgICANCkBAQCAgQEBAICBAQEBAQEBAQCAgQEBAQEBAQEAgIEBAQEBAQEBAICBAQEAgIEBAQCAgICAgICAgICANCkBAISAgIUBAICBAQCEgIEBAQCAgQEAhICBAQEAgICFAQCAgICAgICBAQCEgICFAQCAgICAgICAgICANCiFAISAgQCEhICAhQCEgIEAhQCAgIUAhICBAIUAgICFAISAgICAgICAhQCEgIEAhISAgICAgICAgICANCkAhQEAhQCEgICBAIUAhIUAhICAgQCFAIUAhQCEgICFAISAgICAgICBAIUBAIUAhICAgICAgICAgICANCiEhQCEhISAgICAhIUAhQCEgICAgISEhQCEhISEgICEhISAgICAgICAhIUAhISEgICAgICAgICAgICANCiEhOiA6ISEgICAhITogOiEhICAgISE6ICAhISEgIDohISAgICAgICAhITogOiEhICAgICAgICAgICANCjohOiAgITohICA6ITogICE6ISAgOiE6ICAhOiEgIDohOiAgICAgICA6ITogICE6ISAgICAgICAgICANCiA6OiAgOjo6ICA6OiAgIDo6OiAgOjogICA6OjogICA6OjogOjo6ICAgOjogIDo6OiAgICAgICAgICANCiA6ICAgOjo6ICAgOiAgIDogOiAgIDogICA6IDogICA6OiA6OiA6ICAgOiAgIDo6OiAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiBfX19fX19fXyAgX19fX19fX19fICBfX19fX19fX18gIF9fX19fX19fICBfX19fX19fXyAgX19fICBfXyAgICAgICANCnxcICAgX18gIFx8XF9fXyAgIF9fX1xcX19fICAgX19fXFwgICBfXyAgXHxcICAgX19fX1x8XCAgXHxcICBcICAgICANClwgXCAgXHxcICBcfF9fXyBcICBcX1x8X19fIFwgIFxfXCBcICBcfFwgIFwgXCAgXF9fX3xcIFwgIFwvICAvfF8gICANCiBcIFwgICBfXyAgXCAgIFwgXCAgXCAgICAgXCBcICBcIFwgXCAgIF9fICBcIFwgIFwgICAgXCBcICAgX19fICBcICANCiAgXCBcICBcIFwgIFwgICBcIFwgIFwgICAgIFwgXCAgXCBcIFwgIFwgXCAgXCBcICBcX19fX1wgXCAgXFwgXCAgXCANCiAgIFwgXF9fXCBcX19cICAgXCBcX19cICAgICBcIFxfX1wgXCBcX19cIFxfX1wgXF9fX19fX19cIFxfX1xcIFxfX1wNCiAgICBcfF9ffFx8X198ICAgIFx8X198ICAgICAgXHxfX3wgIFx8X198XHxfX3xcfF9fX19fX198XHxfX3wgXHxfX3wNCg0KDQoNCg=="

options=("Lab 0" "Lab 1" "Lab 2" "Lab 3" "Ctr+C to exit")
width=25
cols=1

for ((i=0;i<${#options[@]};i++)); do 
    string="- ${options[$i]}"
    printf "%s" "$string"
    printf "%$(($width-${#string}))s" " "
    [[ $(((i+1)%$cols)) -eq 0 ]] && echo
done

while true; do

    echo
    read -p "Lab " opt

    case $opt in
        0)
            (cd ./labs/lab-0/ ; chmod +x start.sh ; ./start.sh)
            ;;

        1)
            (cd ./lab-1/ ; chmod +x start.sh ; ./start.sh)
            ;;

        2)
            (cd ./lab-2/ ; chmod +x start.sh ; ./start.sh)
            ;;

        3)
            ;;

        *) ;;
    esac
done

